# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - name: set up node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
      - run: npm install
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "testcafe chrome tests -r allure"
      - name: Generate allure report
      - run: allure generate allure
      - name: Publishing Allure artifact to GitHub Actions
      - uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report